/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CashbookRouteImport } from './routes/cashbook'
import { Route as AiTestRouteImport } from './routes/ai-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartiesIndexRouteImport } from './routes/parties.index'
import { Route as PartiesIdRouteImport } from './routes/parties.$id'
import { Route as InvoiceNewRouteImport } from './routes/invoice.new'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbookRoute = CashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTestRoute = AiTestRouteImport.update({
  id: '/ai-test',
  path: '/ai-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIndexRoute = PartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdRoute = PartiesIdRouteImport.update({
  id: '/parties/$id',
  path: '/parties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceNewRoute = InvoiceNewRouteImport.update({
  id: '/invoice/new',
  path: '/invoice/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-test': typeof AiTestRoute
  '/cashbook': typeof CashbookRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/invoice/new': typeof InvoiceNewRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/': typeof PartiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-test': typeof AiTestRoute
  '/cashbook': typeof CashbookRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/invoice/new': typeof InvoiceNewRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties': typeof PartiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-test': typeof AiTestRoute
  '/cashbook': typeof CashbookRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/invoice/new': typeof InvoiceNewRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/': typeof PartiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-test'
    | '/cashbook'
    | '/chat'
    | '/settings'
    | '/stock'
    | '/invoice/$id'
    | '/invoice/new'
    | '/parties/$id'
    | '/parties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-test'
    | '/cashbook'
    | '/chat'
    | '/settings'
    | '/stock'
    | '/invoice/$id'
    | '/invoice/new'
    | '/parties/$id'
    | '/parties'
  id:
    | '__root__'
    | '/'
    | '/ai-test'
    | '/cashbook'
    | '/chat'
    | '/settings'
    | '/stock'
    | '/invoice/$id'
    | '/invoice/new'
    | '/parties/$id'
    | '/parties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTestRoute: typeof AiTestRoute
  CashbookRoute: typeof CashbookRoute
  ChatRoute: typeof ChatRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  InvoiceNewRoute: typeof InvoiceNewRoute
  PartiesIdRoute: typeof PartiesIdRoute
  PartiesIndexRoute: typeof PartiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbook': {
      id: '/cashbook'
      path: '/cashbook'
      fullPath: '/cashbook'
      preLoaderRoute: typeof CashbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-test': {
      id: '/ai-test'
      path: '/ai-test'
      fullPath: '/ai-test'
      preLoaderRoute: typeof AiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/': {
      id: '/parties/'
      path: '/parties'
      fullPath: '/parties/'
      preLoaderRoute: typeof PartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/parties/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/new': {
      id: '/invoice/new'
      path: '/invoice/new'
      fullPath: '/invoice/new'
      preLoaderRoute: typeof InvoiceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTestRoute: AiTestRoute,
  CashbookRoute: CashbookRoute,
  ChatRoute: ChatRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  InvoiceNewRoute: InvoiceNewRoute,
  PartiesIdRoute: PartiesIdRoute,
  PartiesIndexRoute: PartiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
